1) SELECT A.FULL_NAME, B.TITLE
   FROM AUTHOR AS A
   JOIN BOOK AS B
   ON A.AUTHOR_ID = B.AUTHOR_ID;
2) SELECT A.FULL_NAME, B.TITLE, B.PUBLISH_YEAR
   FROM AUTHOR AS A
   JOIN BOOK AS B
   ON A.AUTHOR_ID = B.AUTHOR_ID AND B.PUBLISH_YEAR > 2005;
3) SELECT B.TITLE, B.PUBLISHING_HOUSE, A.TITLE, A.TYPE_OF_BOOK
   FROM BOOK AS B
   JOIN ADAPTAION AS A
   ON B.BOOK_ID = A.BOOK_ID;
4) SELECT TITLE, PUBLISH_YEAR
   FROM BOOK
   LEFT JOIN BOOK_REVIEW
   ON BOOK.BOOK_ID = BOOK_REVIEW.BOOK_ID
   WHERE  BOOK_REVIEW.BOOK_ID IS NULL
5) SELECT B.BOOK_ID, B.TITLE, A.FULL_NAME 
   FROM BOOK AS B
   LEFT JOIN AUTHOR AS A
   ON B.AUTHOR_ID = A.AUTHOR_ID
   WHERE A.BIRTH_YEAR BETWEEN 1900 AND 1999
6) SELECT B.TITLE, B.RATING
   FROM BOOK AS B
   JOIN AUTHOR AS A
   ON B.AUTHOR_ID = A.AUTHOR_ID
   WHERE A.DEATH_YEAR IS NOT NULL
7) SELECT B.TITLE AS TITLE_OF_BOOK, A.TITLE AS TITLE_OF_ADAPTATION, A.RELEASE_YEAR
   FROM BOOK AS B
   LEFT JOIN ADAPTAION AS A
   ON B.BOOK_ID = A.BOOK_ID
8) SELECT B.BOOK_ID, B.TITLE, BR.REVIEW, BR.NAME_OF_AUTHOR
   FROM BOOK_REVIEW AS BR
   RIGHT JOIN BOOK AS B
   ON BR.BOOK_ID = B.BOOK_ID




-- TABLE AUTHOR

CREATE TABLE AUTHOR
(
	AUTHOR_ID SERIAL PRIMARY KEY,
	FULL_NAME CHARACTER VARYING(25),
	BIRTH_YEAR smallint check(BIRTH_YEAR between 0 and extract(year from current_date)),
	DEATH_YEAR smallint check(DEATH_YEAR between 0 and extract(year from current_date))
);

INSERT INTO AUTHOR  (AUTHOR_ID, AUTHOR_NAME, BIRTH_YEAR, DEATH_YEAR) VALUES (1, 'Georgie', '1945-09-02', NULL);
INSERT INTO AUTHOR  (AUTHOR_ID, AUTHOR_NAME, BIRTH_YEAR, DEATH_YEAR) VALUES (2, 'Nan', '1943-05-22', '2019-04-25');


-- TABLE BOOK

CREATE TABLE BOOK
(
	BOOK_ID SERIAL PRIMARY KEY,
	AUTHOR_ID INTEGER REFERENCES AUTHOR(AUTHOR_ID),
	TITLE CHARACTER VARYING(50),
	PUBLISH_YEAR smallint check(PUBLISH_YEAR between 0 and extract(year from current_date)),
	PUBLISHING_HOUSE CHARACTER VARYING(50),
	RATING REAL
);

INSERT INTO BOOK  (BOOK_ID, AUTHOR_ID, TITLE, PUBLISH_YEAR, PUBLISHING_HOUSE, RATING) VALUES (1, NULL, 'Denice', '2001-05-16', 'Lowth', 1.6);
INSERT INTO BOOK  (BOOK_ID, AUTHOR_ID, TITLE, PUBLISH_YEAR, PUBLISHING_HOUSE, RATING) VALUES (2, NULL, 'Dennet', '2018-12-22', 'Drable', 3.0);
INSERT INTO BOOK  (BOOK_ID, AUTHOR_ID, TITLE, PUBLISH_YEAR, PUBLISHING_HOUSE, RATING) VALUES (3, 3, 'Letty', '2012-03-03', 'Pryde', 2.3);


-- TABLE ADAPTATION

CREATE TABLE ADAPTAION
(
	BOOK_ID INTEGER REFERENCES BOOK(BOOK_ID),
	TYPE_OF_BOOK CHARACTER VARYING(50),
	TITLE CHARACTER VARYING(50),
	RELEASE_YEAR SMAILLINT CHECK(RELEASE_YEAR between 0 and extract(year from current_date)),
	RATING REAL
);

INSERT INTO ADAPTATION  (BOOK_ID, ADAP_TYPE, TITLE, PUBLISH_YEAR, RATING) values (1, 'movie', 'Secrets of Jonathan Sperry, The', '2011-01-25', 1.6);
INSERT INTO ADAPTATION  (BOOK_ID, ADAP_TYPE, TITLE, PUBLISH_YEAR, RATING) values (3, 'movie', 'The Legend of Awesomest Maximus', '2016-03-10', 3.9);
INSERT INTO ADAPTATION  (BOOK_ID, ADAP_TYPE, TITLE, PUBLISH_YEAR, RATING) values (5, 'game', 'Robots', '2010-05-20', 4.8);


-- TABLE BOOK REVIEW

CREATE TABLE BOOK_REVIEW
(
	BOOK_ID INTEGER REFERENCES BOOK(BOOK_ID),
	REVIEW CHARACTER VARYING(100),
	NAME_OF_AUTHOR CHARACTER VARYING(25)
);


INSERT INTO BOOK_REVIEW (BOOK_ID, REVIEW, AUTHOR) VALUES (1, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Heidie');
INSERT INTO BOOK_REVIEW (BOOK_ID, REVIEW, AUTHOR) VALUES (2, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Torrence');




