1) SELECT A.FULL_NAME, B.TITLE
   FROM AUTHOR AS A
   JOIN BOOK AS B
   ON A.AUTHOR_ID = B.AUTHOR_ID;
2) SELECT A.FULL_NAME, B.TITLE, B.PUBLISH_YEAR
   FROM AUTHOR AS A
   JOIN BOOK AS B
   ON A.AUTHOR_ID = B.AUTHOR_ID AND B.PUBLISH_YEAR > 2005;
3) SELECT B.TITLE, B.PUBLISHING_HOUSE, A.TITLE, A.TYPE_OF_BOOK
   FROM BOOK AS B
   JOIN ADAPTAION AS A
   ON B.BOOK_ID = A.BOOK_ID;
4) SELECT TITLE, PUBLISH_YEAR
   FROM BOOK
   LEFT JOIN BOOK_REVIEW
   ON BOOK.BOOK_ID = BOOK_REVIEW.BOOK_ID
   WHERE  BOOK_REVIEW.BOOK_ID IS NULL
5) SELECT B.BOOK_ID, B.TITLE, A.FULL_NAME 
   FROM BOOK AS B
   LEFT JOIN AUTHOR AS A
   ON B.AUTHOR_ID = A.AUTHOR_ID
   WHERE A.BIRTH_YEAR < 2000
6) SELECT B.TITLE, B.RATING
   FROM BOOK AS B
   JOIN AUTHOR AS A
   ON B.AUTHOR_ID = A.AUTHOR_ID
   WHERE A.DEATH_YEAR IS NOT NULL
7) SELECT B.TITLE AS TITLE_OF_BOOK, A.TITLE AS TITLE_OF_ADAPTATION, A.RELEASE_YEAR
   FROM BOOK AS B
   LEFT JOIN ADAPTAION AS A
   ON B.BOOK_ID = A.BOOK_ID
8) SELECT B.BOOK_ID, B.TITLE, BR.REVIEW, BR.NAME_OF_AUTHOR
   FROM BOOK_REVIEW AS BR
   RIGHT JOIN BOOK AS B
   ON BR.BOOK_ID = B.BOOK_ID